export const PRODUCTO_AGREGAR = "PRODUCTO_AGREGAR";
export const PRODUCTO_AGREGAR_EXITO = "PRODUCTO_AGREGAR_EXITO";
export const PRODUCTO_AGREGAR_ERROR = "PRODUCTO_AGREGAR_ERROR";

export const PRODUCTO_DESCARGAR = "PRODUCTO_DESCARGAR"
export const PRODUCTO_DESCARGAR_EXITO = "PRODUCTO_DESCARGAR_EXITO"
export const PRODUCTO_DESCARGAR_ERROR = "PRODUCTO_DESCARGAR_ERROR"
