export const PRODUCTO_AGREGAR = "PRODUCTO_AGREGAR";
export const PRODUCTO_AGREGAR_EXITO = "PRODUCTO_AGREGAR_EXITO";
export const PRODUCTO_AGREGAR_ERROR = "PRODUCTO_AGREGAR_ERROR";

export const PRODUCTO_DESCARGAR = "PRODUCTO_DESCARGAR"
export const PRODUCTO_DESCARGAR_EXITO = "PRODUCTO_DESCARGAR_EXITO"
export const PRODUCTO_DESCARGAR_ERROR = "PRODUCTO_DESCARGAR_ERROR"

export const PRODUCTO_ELIMINAR = "PRODUCTO_ELIMINAR"
export const PRODUCTO_ELIMINAR_EXITO = "PRODUCTO_ELIMINAR_EXITO"
export const PRODUCTO_ELIMINAR_ERROR = "PRODUCTO_ELIMINAR_ERROR"

export const PRODUCTO_EDITAR = "PRODUCTO_EDITAR"
export const PRODUCTO_EDITAR_INICIO = "PRODUCTO_EDITAR_INICIO"
export const PRODUCTO_EDITAR_EXITO = "PRODUCTO_EDITAR_EXITO"
export const PRODUCTO_EDITAR_ERROR = "PRODUCTO_EDITAR_ERROR"
